name: Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  conventional-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Conventional Commits Check
        uses: webiny/action-conventional-commits@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
